<?php

declare(strict_types=1);

namespace Innobrain\OnOfficeAdapter\Enums;

enum OnOfficeError: int
{
    case Ok = 0;
    case Unknown_Error_Occurred = 1;
    case Maximum_Stack_Depth_Exceeded = 3;
    case Invalid_Or_Malformed_JSON = 4;
    case Control_Character_Error = 5;
    case Syntax_Error = 6;
    case Malformed_UTF_8_Characters = 7;
    case Unknown_Error_During_JSON_Conversion = 8;
    case Empty_Request = 9;
    case Missing_Or_Invalid_Element_Token = 13;
    case Missing_Or_Invalid_Element_Request = 14;
    case Missing_Or_Invalid_Element_Actions = 15;
    case Missing_Or_Invalid_Attribute_Actionid = 16;
    case Empty_Attribute_Actionid = 17;
    case Missing_Or_Invalid_Attribute_Resourceid = 18;
    case Missing_Or_Invalid_Attribute_Resourcetype = 19;
    case Missing_Or_Invalid_Element_Parameters = 20;
    case Empty_Parameter_Name = 21;
    case Not_Authenticated = 22;
    case Missing_Configuration_For_ActionId = 23;
    case Missing_Configuration_For_ResourceId = 24;
    case Missing_Configuration_For_ResourceType = 25;
    case Action_Processor_Not_Found = 26;
    case Unknown_XML_Error = 27;
    case Error_During_Client_Registration = 28;
    case Error_During_Client_Removal = 29;
    case Error_Retrieving_Client_Information = 30;
    case Error_Updating_Client_Information = 31;
    case Error_Retrieving_Client_Ids = 32;
    case Error_Creating_Token = 34;
    case Error_Revoking_Token = 35;
    case Error_Updating_Token_Expiration_Date = 36;
    case Error_Getting_Token_Data = 37;
    case Missing_Authentication_Type = 38;
    case Unknown_Authentication_Type = 39;
    case Invalid_User_Credentials = 40;
    case Customer_Unknown = 41;
    case Customer_Is_Not_Active = 42;
    case User_Unknown = 43;
    case Invalid_Refresh_Token_Credentials = 44;
    case Refresh_Token_Is_Not_Valid = 45;
    case Clientid_Mismatch = 46;
    case Client_Does_Not_Exist = 47;
    case Client_Access_Revoked = 48;
    case Secret_Is_Wrong = 49;
    case Missing_Email_Identity = 50;
    case Invalid_Email_Identity = 51;
    case List_Of_Receivers_Is_Not_An_Array = 52;
    case Missing_Receivers = 53;
    case Invalid_Pdf_Expose_Identifier = 54;
    case Invalid_Receivers = 55;
    case Error_During_Sending_Mail = 56;
    case Macro_Needs_Object_And_Expose = 57;
    case Missing_Message_Id = 58;
    case Missing_Email_Uid = 59;
    case Missing_Email_Folder = 60;
    case Error_During_Email_Retrieval = 61;
    case Email_Does_Not_Exist_Anymore = 62;
    case Mismatching_Message_Id = 63;
    case Wrong_Format_For_AddressId = 64;
    case Wrong_Format_For_EstateId = 65;
    case Index_Must_Be_Positiv = 67;
    case Index_Must_Be_Numeric = 68;
    case Search_Cannot_Be_Empty = 69;
    case Fetching_Record_Entries = 70;
    case Missing_Template_Type = 71;
    case Invalid_Template_Type = 72;
    case EstateIds_Must_Be_An_Array = 73;
    case Given_Element_Or_Parameter_Was_Expected_To_Be_An_Array = 74;
    case Unknown_Field = 75;
    case Invalid_Multiselect_Key = 76;
    case Invalid_Singleselect_Key = 77;
    case Entry_Could_Not_Be_Created = 78;
    case Missing_Record_Id = 79;
    case Unknown_Record = 80;
    case Missing_Type_For_Address_Phone_Action = 81;
    case Invalid_Type_For_Address_Phone_Action = 82;
    case Unknown_Address_Phone_Record = 83;
    case Invalid_Address_Phone_Record = 84;
    case Missing_Address_Phone_Value = 85;
    case Missing_Address_Phone_Record_Identifier = 86;
    case Ambiguous_Address_Phone_Record_Identifier = 87;
    case Entry_Could_Not_Be_Modified = 88;
    case Missing_Device_Type = 89;
    case Unknown_Device_Type = 90;
    case Start_Date_Missing = 91;
    case End_Date_Missing = 92;
    case Start_Date_Is_Greater_Than_End_Date = 93;
    case Unknown_Email_Folder = 94;
    case Unknown_Search_Criteria = 95;
    case Missing_Address_Record_Id = 96;
    case Error_In_Action = 97;
    case Missing_Relation_To_Address_And_Or_Estate_Record = 98;
    case Address_Record_Ids_Not_In_Array = 99;
    case Unknown_Kind_Of_Action = 100;
    case Unknown_Type_Of_Action = 101;
    case Missing_Accountname_Or_Password = 102;
    case Unknown_Account = 103;
    case User_Is_Not_Active = 104;
    case Username_Or_Password_Incorrect_4_Tries_Remaining = 105;
    case Username_Or_Password_Incorrect_3_Tries_Remaining = 106;
    case Username_Or_Password_Incorrect_2_Tries_Remaining = 107;
    case Username_Or_Password_Incorrect_1_Try_Remaining = 108;
    case Missing_Registry_Key = 109;
    case Missing_Estate_Record_Id = 110;
    case Missing_Or_Invalid_Data_For_PDF_Generation = 111;
    case PDF_Generation_Failed = 112;
    case Missing_Note = 113;
    case Missing_File_Name = 114;
    case PDF_Data_Null_After_Generation = 115;
    case Missing_Date = 116;
    case Missing_Appointment_ID = 117;
    case Missing_Effective_Date = 119;
    case Invalid_Appointment_Id = 121;
    case Invalid_Date = 122;
    case Error_Closing_Appointment_Tracking_Entry = 123;
    case Error_Creating_Appointment_Tracking_Entry = 124;
    case Missing_Text_For_Resolver = 125;
    case Text_Resolving_Failed = 126;
    case File_Not_Found = 127;
    case Fileupload_Is_Missing_Temporary_Upload_File = 129;
    case No_Survey_Id_Or_No_Survey_With_Given_Id_Found_In_Database = 130;
    case Address_Creation_Without_Proper_User_Rights = 131;
    case No_Or_Unknown_Relation_Given = 132;
    case No_Email_For_Given_Message_Id = 133;
    case Type_Of_User_Not_Allowed_For_Login = 134;
    case Unknown_Login_State = 135;
    case Your_Timestamp_Is_Too_Old_Or_Your_Server_Time_Is_Wrong = 136;
    case The_HMAC_Is_Invalid = 137;
    case Unknown_Field_In_Task_Data = 138;
    case Missing_Params_Picture_Categories_Or_Estateids = 139;
    case Unknown_Field_141 = 141;
    case Unknown_Operator = 142;
    case Unknown_Field_In_Estate_Data = 143;
    case Invalid_Field_In_Input_Data = 144;
    case Unknown_Field_145 = 145;
    case Invalid_Recipient = 146;
    case No_Mails_Sent = 148;
    case No_Read_Permission_For_This_Estate = 149;
    case Username_Or_Password_Incorrect_Account_Disabled = 150;
    case The_Search_String_Has_Not_Enough_Characters = 151;
    case Unsupported_Address_Completion_Mode = 152;
    case Token_Data_By_Given_Access_Token_Invalid = 153;
    case Unknown_Calendar_Field = 154;
    case Missing_Permission_Check_In_Action_Processor = 155;
    case Access_Violation = 156;
    case Access_From_This_IP_Not_Allowed = 158;
    case From_Call_To_Pdftk = 159;
    case Invalid_Language = 160;
    case Document_Attribute_Exists = 161;
    case Invalid_File_Type = 162;
    case Invalid_Name_For_Module = 163;
    case Incomplete_Parameters_For_Geo_Range_Search = 164;
    case Tried_To_Send_A_Message_To_A_Unknown_User_Room = 165;
    case Finding_Dependent_Field_Values = 166;
    case Missing_Parameter = 167;
    case Entry_Could_Not_Be_Deleted = 168;
    case Appointment_Not_Found = 169;
    case No_Read_Permission_For_This_User = 170;
    case No_Singleselect_Or_Multiselect_Field = 171;
    case Invalid_Image_Format = 172;
    case Could_Not_Create_Relation_Between_Address_And_Estate = 173;
    case Missing_Permission_To_Perform_Modify_Call = 174;
    case Customer_Context_Switch_Failed = 175;
    case User_Context_Switch_Failed = 176;
    case Parameter_Cache_Does_Not_Exist = 177;
    case Missing_Entries_In_Parameter_Cache = 178;
    case Could_Not_Create_Relation_Cause_Of_Invalid_Relationinfos = 179;
    case Could_Not_Modify_Relation_Relation_Does_Not_Exist = 180;
    case Could_Not_Modify_Relation_Invalid_Relationinfos_Given = 181;
    case Could_Not_Modify_Relation_Relation_Is_Not_Updateable = 182;
    case User_Access_Not_Granted = 183;
    case User_Id_Is_Not_Existing_Or_Inactive = 184;
    case Missing_Or_Invalid_Record_Ids = 185;
    case Userid_Must_Be_An_Integer = 186;
    case Given_Element_Or_Parameter_Was_Not_Expected_To_Be_An_Array = 187;
    case The_User_Data_Could_Not_Be_Found = 188;
    case The_Transaction_Could_Not_Be_Found = 189;
    case The_Time_To_Call_The_Transaction_Has_Expired = 190;
    case No_Read_Access_To_Email_Template = 191;
    case Tried_To_Read_Messages_From_An_Unknown_User_Room = 192;
    case Parameter_Extendedclaim_Is_Required_But_Missing_Empty_Or_Invalid = 193;
    case Wrong_Type_For_At_Least_One_Of = 194;
    case Parameter_Objids_Is_Required_But_Missing = 196;
    case Resourceid_Is_No_Main_Id = 198;
    case Not_Implemented = 199;
    case Parameter_Extendedclaim_Is_Outdated = 201;
    case Invalid_Username_Or_Password_For_Z_Push_Login = 202;
    case Z_Push_Account_Locked_Too_Many_Invalid_Login_Requests = 203;
    case Unknown_Searchcriteria_Mode = 204;
    case Transaction_Id_Does_Not_Match_To_The_Customer = 205;
    case Unknown_Z_Push_Address_Phone_Mapping = 206;
    case Empty_Z_Push_Address_Phone_Mapping = 207;
    case Using_Parameter_Zpmapping_Is_Not_Allowed_When_Using_Other_Parameters_For_Phone_Fax_Email = 208;
    case Missing_Key_Value_S_In_Zpmapping = 209;
    case Transaction_Can_T_Be_Refunded = 210;
    case Email_Could_Not_Be_Sent = 211;
    case Unknown_Sort_Field = 212;
    case Invalid_Filename = 213;
    case Invalid_Price_Format = 214;
    case Parameter_Must_Not_Be_Null = 215;
    case Sync_Module_For_Customer_Is_Not_Active = 216;
    case Sync_Outlooksync_Flag_For_Enterprise_User_Is_Disabled = 217;
    case ZPush_Is_Not_Active_For_This_User = 218;
    case N_N_Relations_Are_Not_Allowed = 219;
    case Unknown_Origincontact = 220;
    case Unknown_Feature = 221;
    case Invalid_Value_For_Cost_Not_Numeric_Or_Less_Than_0 = 222;
    case Invalid_Value_For_Duration_Not_Numeric_Or_Less_Than_0 = 223;
    case Can_Not_Set_Reason_Of_Cancellation_Advisory_Level_Missing = 224;
    case Unknown_Advisory_Level = 225;
    case Unknown_Reason_Of_Cancelation = 226;
    case Given_Element_Or_Parameter_Was_Expected_To_Be_A_String = 227;
    case Given_Element_Or_Parameter_Was_Expected_To_Be_An_Integer = 228;
    case Given_Element_Or_Parameter_Was_Expected_To_Be_An_Float = 229;
    case Missing_Date_Interval = 230;
    case Invalid_Date_Interval = 231;
    case Multiselect_Fields_Can_Only_Be_Filtered_With = 232;
    case Missing_Email_Template = 233;
    case Unknown_Record_Id = 235;
    case Parameter_Data_Must_Be_Of_Type_String = 236;
    case Missing_Filter_Beratungsebene_For = 237;
    case The_Attachment_Is_Too_Big = 238;
    case Upload_Failed_Estate_Already_Has_A_Title_Picture = 239;
    case Call_For_Marketplace_Api_Users_Not_Allowed = 240;
    case Filters_Can_Only_Be_Used_When_Reading_Out_Appointments_Of_A_Period = 241;
    case While_Sending_The_Size_Of_The_Attachment_May_Have_Been_Exceeded = 242;
    case The_HMAC_Is_Invalid_Should_Be_Passed_As_String = 243;
    case When_Attaching_An_Expose_Only_One_Pdf_Letter_Can_Be_Attached = 244;
    case No_Read_Access_To_Pdf_Form = 245;
    case No_Read_Access_To_Pdf_Letter = 246;
    case Missing_Or_Invalid_Element_Action = 247;
    case No_Matching_Extendedclaim = 248;
    case Invalid_Zpushuuid = 249;
    case Maximum_Length_300_Of_Zpushuuid_Exceeded = 250;
    case Unknown_User = 251;
    case Unknown_Value_In_Select_Field = 252;
    case No_Access_To = 253;
    case Missing_Mandatory_Field = 254;
    case Invalid_Value_For_Parameter = 255;
    case Parameter_Listlimit_Is_Mandatory_And_Must_Be_0 = 256;
    case An_Occurred_While_Validating_The_Filter = 257;
    case The_Default_Entry_For_Must_Be_Passed_Also_As_Normal_Private_Or_Business_Entry = 258;
    case An_Occurred_Modifying_The_Default_Entry = 259;
    case The_Default_Entry_For_Phone_Must_Be_Passed_Also_As_Normal_Private_Business_Or_Mobile_Entry = 260;
    case Missing_Write_Right_For_Addresses_With_Ids = 261;
    case Missing_Write_Right_For_Estates_With_Ids = 262;
    case Address_Must_Be_A_Real_Estate_Agent = 263;
    case Too_Many_Items_In_Worklist = 264;
    case Too_Few_Items_In_Worklist = 265;
    case WorkingList_Name_Already_Exists = 266;
    case Cannot_Set_Visibility = 267;
    case Cannot_Set_STV_Flag = 268;
    case WorkingList_Type_Not_Allowed = 269;
    case Wrong_Parameter_Type_For = 270;
    case Invalid_Web_Expose_Identifier = 271;
    case Invalid_Group_ID = 272;
    case WorkingList_Name_Cannot_Be_Empty = 273;
    case Mail_Already_Deleted = 274;
    case Mail_Couldn_t_Be_Deleted = 275;
    case Mail_Could_Not_Be_Found = 276;
    case Mail_Couldn_t_Be_Moved = 277;
    case Deauthenticate_Can_Only_Be_Called_At_The_End = 278;
    case Unknown_ResourceId = 279;
    case Flag_Could_Not_Be_Set = 281;
    case No_Valid_Parameter_Given = 282;
    case Email_Could_Not_Be_Found = 283;
    case The_Requested_Filterid_Is_Unknown = 284;
    case Mail_Could_Not_Be_Loaded = 285;
    case User_Is_Not_Active_286 = 286;
    case Folder_Not_Found = 287;
    case Start_Modified_Date_Is_Greater_Than_End_Modified_Date = 288;
    case Missing_Date_Period = 289;
    case Parameter_Location_Holds_Wrong_Values = 290;
    case Fieldname_Is_Not_A_String = 291;
    case Unknown_Address_Record_Id = 292;
    case Unknown_Estate_Record_Id = 293;
    case Invalid_Data_Type_For_Parameter = 294;
    case Given_Groups_Has_To_Be_An_Array_Of_IDs = 295;
    case Either_AddressId_Or_AddressIds_Is_Allowed = 297;
    case AddressIds_Must_Be_Of_Type_Array = 298;
    case AddressIds_Values_Must_Be_Of_Type_Integer = 299;
    case Invalid_Address_Phone_Value = 300;
    case Given_Users_Has_To_Be_An_Array_Of_IDs = 301;
    case This_Action_Support_Only_Up_To_500_Ids = 302;
    case Error_Creating_Request = 303;
    case Module_And_View_Parameters_Must_Not_Be_Empty = 304;

    case UNKNOWN = 999;

    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }

    public static function errorTexts(): array
    {
        return [
            self::Ok->value => 'OK',
            self::Unknown_Error_Occurred->value => 'Unknown error occurred',
            self::Maximum_Stack_Depth_Exceeded->value => 'The maximum stack depth has been exceeded',
            self::Invalid_Or_Malformed_JSON->value => 'Invalid or malformed JSON',
            self::Control_Character_Error->value => 'Control character error, possibly incorrectly encoded',
            self::Syntax_Error->value => 'Syntax error',
            self::Malformed_UTF_8_Characters->value => 'Malformed UTF-8 characters, possibly incorrectly encoded',
            self::Unknown_Error_During_JSON_Conversion->value => 'Unknown error during JSON conversion',
            self::Empty_Request->value => 'Empty request',
            self::Missing_Or_Invalid_Element_Token->value => 'Missing or invalid element: token',
            self::Missing_Or_Invalid_Element_Request->value => 'Missing or invalid element: request',
            self::Missing_Or_Invalid_Element_Actions->value => 'Missing or invalid element: actions',
            self::Missing_Or_Invalid_Attribute_Actionid->value => 'Missing or invalid attribute: actionid',
            self::Empty_Attribute_Actionid->value => 'Empty attribute: actionid',
            self::Missing_Or_Invalid_Attribute_Resourceid->value => 'Missing or invalid attribute: resourceid',
            self::Missing_Or_Invalid_Attribute_Resourcetype->value => 'Missing or invalid attribute: resourcetype',
            self::Missing_Or_Invalid_Element_Parameters->value => 'Missing or invalid element: parameters',
            self::Empty_Parameter_Name->value => 'Empty parameter name',
            self::Not_Authenticated->value => 'Not authenticated',
            self::Missing_Configuration_For_ActionId->value => 'Missing configuration for actionId "%s"',
            self::Missing_Configuration_For_ResourceId->value => 'Missing configuration for resourceId "%s"',
            self::Missing_Configuration_For_ResourceType->value => 'Missing configuration for resourceType "%s"',
            self::Action_Processor_Not_Found->value => 'Action processor must be an instance of SmartMlInterfaceActionProcessor',
            self::Unknown_XML_Error->value => 'Instance of XmlSmartMlData expected',
            self::Error_During_Client_Registration->value => 'Error during client registration!',
            self::Error_During_Client_Removal->value => 'Error during client removal!',
            self::Error_Retrieving_Client_Information->value => 'Error retrieving client information',
            self::Error_Updating_Client_Information->value => 'Error updating client information!',
            self::Error_Retrieving_Client_Ids->value => 'Error retrieving client ids',
            self::Error_Creating_Token->value => 'Error creating token',
            self::Error_Revoking_Token->value => 'Error revoking token',
            self::Error_Updating_Token_Expiration_Date->value => 'Error updating token expiration date',
            self::Error_Getting_Token_Data->value => 'Error getting token data!',
            self::Missing_Authentication_Type->value => 'Missing authentication type',
            self::Unknown_Authentication_Type->value => 'Unknown authentication type',
            self::Invalid_User_Credentials->value => 'Invalid user credentials',
            self::Customer_Unknown->value => 'Customer unknown!',
            self::Customer_Is_Not_Active->value => 'Customer is not active!',
            self::User_Unknown->value => 'User unknown!',
            self::Invalid_Refresh_Token_Credentials->value => 'Invalid refresh token credentials. Some informations are empty!',
            self::Refresh_Token_Is_Not_Valid->value => 'Refresh token is not valid!',
            self::Clientid_Mismatch->value => 'Clientid mismatch',
            self::Client_Does_Not_Exist->value => 'Client does not exist!',
            self::Client_Access_Revoked->value => 'Client access revoked!',
            self::Secret_Is_Wrong->value => 'Secret is wrong!',
            self::Missing_Email_Identity->value => 'Missing email identity',
            self::Invalid_Email_Identity->value => 'Invalid email identity',
            self::List_Of_Receivers_Is_Not_An_Array->value => 'List of receivers is not an array',
            self::Missing_Receivers->value => 'Missing receivers',
            self::Invalid_Pdf_Expose_Identifier->value => 'Invalid pdf exposé identifier',
            self::Invalid_Receivers->value => 'Invalid receivers',
            self::Error_During_Sending_Mail->value => 'Error during sending mail!',
            self::Macro_Needs_Object_And_Expose->value => 'Macro needs object and expose!',
            self::Missing_Message_Id->value => 'Missing message id',
            self::Missing_Email_Uid->value => 'Missing email uid',
            self::Missing_Email_Folder->value => 'Missing email folder',
            self::Error_During_Email_Retrieval->value => 'Error during email retrieval',
            self::Email_Does_Not_Exist_Anymore->value => 'Email does not exist (anymore)',
            self::Mismatching_Message_Id->value => 'Mismatching message id',
            self::Wrong_Format_For_AddressId->value => 'Wrong format for addressId',
            self::Wrong_Format_For_EstateId->value => 'Wrong format for estateId',
            self::Index_Must_Be_Positiv->value => 'Index must be positiv!',
            self::Index_Must_Be_Numeric->value => 'Index must be numeric!',
            self::Search_Cannot_Be_Empty->value => 'Search cannot be empty',
            self::Fetching_Record_Entries->value => 'Error fetching record entries',
            self::Missing_Template_Type->value => 'Missing template type',
            self::Invalid_Template_Type->value => 'Invalid template type',
            self::EstateIds_Must_Be_An_Array->value => 'EstateIds must be an array',
            self::Given_Element_Or_Parameter_Was_Expected_To_Be_An_Array->value => 'Given element or parameter was expected to be an array',
            self::Unknown_Field->value => 'Unknown field: "%s"',
            self::Invalid_Multiselect_Key->value => 'Invalid multiselect key: %s',
            self::Invalid_Singleselect_Key->value => 'Invalid singleselect key: %s',
            self::Entry_Could_Not_Be_Created->value => 'Entry could not be created',
            self::Missing_Record_Id->value => 'Missing record id',
            self::Unknown_Record->value => 'Unknown record. Record may not exist or the permission rights are not set accordingly for this action.',
            self::Missing_Type_For_Address_Phone_Action->value => 'Missing type for address phone action',
            self::Invalid_Type_For_Address_Phone_Action->value => 'Invalid type for address phone action',
            self::Unknown_Address_Phone_Record->value => 'Unknown address phone record',
            self::Invalid_Address_Phone_Record->value => 'Invalid address phone record',
            self::Missing_Address_Phone_Value->value => 'Missing address phone value',
            self::Missing_Address_Phone_Record_Identifier->value => 'Missing address phone record identifier',
            self::Ambiguous_Address_Phone_Record_Identifier->value => 'Ambiguous address phone record identifier',
            self::Entry_Could_Not_Be_Modified->value => 'Entry could not be modified',
            self::Missing_Device_Type->value => 'Missing device type',
            self::Unknown_Device_Type->value => 'Unknown device type',
            self::Start_Date_Missing->value => 'Start date missing',
            self::End_Date_Missing->value => 'End date missing',
            self::Start_Date_Is_Greater_Than_End_Date->value => 'Start date is greater than end date',
            self::Unknown_Email_Folder->value => 'Unknown email folder "%s"',
            self::Unknown_Search_Criteria->value => 'Unknown search criteria',
            self::Missing_Address_Record_Id->value => 'Missing address record id',
            self::Error_In_Action->value => 'Error in action',
            self::Missing_Relation_To_Address_And_Or_Estate_Record->value => 'Missing relation to address and/or estate record',
            self::Address_Record_Ids_Not_In_Array->value => 'Address record ids not in array',
            self::Unknown_Kind_Of_Action->value => 'Unknown kind of action "%s"',
            self::Unknown_Type_Of_Action->value => 'Unknown type of action "%s"',
            self::Missing_Accountname_Or_Password->value => 'Missing accountname or password',
            self::Unknown_Account->value => 'Unknown account',
            self::User_Is_Not_Active->value => 'User is not active',
            self::Username_Or_Password_Incorrect_4_Tries_Remaining->value => 'Username or password incorrect. 4 tries remaining',
            self::Username_Or_Password_Incorrect_3_Tries_Remaining->value => 'Username or password incorrect. 3 tries remaining',
            self::Username_Or_Password_Incorrect_2_Tries_Remaining->value => 'Username or password incorrect. 2 tries remaining',
            self::Username_Or_Password_Incorrect_1_Try_Remaining->value => 'Username or password incorrect. 1 try remaining',
            self::Missing_Registry_Key->value => 'Missing registry key',
            self::Missing_Estate_Record_Id->value => 'Missing estate record id',
            self::Missing_Or_Invalid_Data_For_PDF_Generation->value => 'Missing or invalid data for PDF generation',
            self::PDF_Generation_Failed->value => 'PDF generation failed',
            self::Missing_Note->value => 'Missing note',
            self::Missing_File_Name->value => 'Missing file name',
            self::PDF_Data_Null_After_Generation->value => 'PDF data null after generation',
            self::Missing_Date->value => 'Missing date',
            self::Missing_Appointment_ID->value => 'Missing appointment ID',
            self::Missing_Effective_Date->value => 'Missing effective date',
            self::Invalid_Appointment_Id->value => 'Invalid appointment id',
            self::Invalid_Date->value => 'Invalid date',
            self::Error_Closing_Appointment_Tracking_Entry->value => 'Error closing appointment tracking entry',
            self::Error_Creating_Appointment_Tracking_Entry->value => 'Error creating appointment tracking entry',
            self::Missing_Text_For_Resolver->value => 'Missing text for resolver',
            self::Text_Resolving_Failed->value => 'Text resolving failed',
            self::File_Not_Found->value => 'File not found',
            self::Fileupload_Is_Missing_Temporary_Upload_File->value => 'Fileupload is missing temporary upload file',
            self::No_Survey_Id_Or_No_Survey_With_Given_Id_Found_In_Database->value => 'No survey id or no survey with given id found in database',
            self::Address_Creation_Without_Proper_User_Rights->value => 'Address creation without proper user rights',
            self::No_Or_Unknown_Relation_Given->value => 'No or unknown relation given',
            self::No_Email_For_Given_Message_Id->value => 'No email for given message id',
            self::Type_Of_User_Not_Allowed_For_Login->value => 'Type of user not allowed for login',
            self::Unknown_Login_State->value => 'Unknown login state',
            self::Your_Timestamp_Is_Too_Old_Or_Your_Server_Time_Is_Wrong->value => 'Your timestamp is too old or your server time is wrong.',
            self::The_HMAC_Is_Invalid->value => 'The HMAC is invalid.',
            self::Unknown_Field_In_Task_Data->value => 'Unknown field in task data',
            self::Missing_Params_Picture_Categories_Or_Estateids->value => 'Missing params "picture categories" or "estateids"',
            self::Unknown_Field_141->value => 'Unknown field: %s',
            self::Unknown_Operator->value => 'Unknown operator: %s',
            self::Unknown_Field_In_Estate_Data->value => 'Unknown field in estate data: %s',
            self::Invalid_Field_In_Input_Data->value => 'Invalid field in input data: "%s"',
            self::Unknown_Field_145->value => 'Unknown field: %s',
            self::Invalid_Recipient->value => 'Invalid recipient',
            self::No_Mails_Sent->value => 'No mails sent',
            self::No_Read_Permission_For_This_Estate->value => 'No read permission for this estate',
            self::Username_Or_Password_Incorrect_Account_Disabled->value => 'Username or password incorrect. Account disabled',
            self::The_Search_String_Has_Not_Enough_Characters->value => 'The search string has not enough characters',
            self::Unsupported_Address_Completion_Mode->value => 'Unsupported address completion mode',
            self::Token_Data_By_Given_Access_Token_Invalid->value => 'Token data by given access token invalid',
            self::Unknown_Calendar_Field->value => 'Unknown calendar field',
            self::Missing_Permission_Check_In_Action_Processor->value => 'Missing permission check in action processor',
            self::Access_Violation->value => 'Access violation',
            self::Access_From_This_IP_Not_Allowed->value => 'Access from this IP not allowed',
            self::From_Call_To_Pdftk->value => 'Error from call to pdftk',
            self::Invalid_Language->value => 'Invalid language: "%s"',
            self::Document_Attribute_Exists->value => 'Document attribute exists',
            self::Invalid_File_Type->value => 'Invalid file type',
            self::Invalid_Name_For_Module->value => 'Invalid name for module',
            self::Incomplete_Parameters_For_Geo_Range_Search->value => 'Incomplete parameters for geo range search',
            self::Tried_To_Send_A_Message_To_A_Unknown_User_Room->value => 'Tried to send a message to a unknown user/room',
            self::Finding_Dependent_Field_Values->value => 'Error finding dependent field values',
            self::Missing_Parameter->value => 'Missing parameter "%s"',
            self::Entry_Could_Not_Be_Deleted->value => 'Entry could not be deleted',
            self::Appointment_Not_Found->value => 'Appointment not found',
            self::No_Read_Permission_For_This_User->value => 'No read permission for this user',
            self::No_Singleselect_Or_Multiselect_Field->value => 'No singleselect- or multiselect field',
            self::Invalid_Image_Format->value => 'Invalid image format',
            self::Could_Not_Create_Relation_Between_Address_And_Estate->value => 'Could not create relation between address and estate',
            self::Missing_Permission_To_Perform_Modify_Call->value => 'Missing permission to perform modify call',
            self::Customer_Context_Switch_Failed->value => 'Customer context switch failed',
            self::User_Context_Switch_Failed->value => 'User context switch failed',
            self::Parameter_Cache_Does_Not_Exist->value => 'Parameter cache does not exist',
            self::Missing_Entries_In_Parameter_Cache->value => 'Missing entries in parameter cache',
            self::Could_Not_Create_Relation_Cause_Of_Invalid_Relationinfos->value => 'Could not create relation cause of invalid relationinfos',
            self::Could_Not_Modify_Relation_Relation_Does_Not_Exist->value => 'Could not modify relation, relation does not exist',
            self::Could_Not_Modify_Relation_Invalid_Relationinfos_Given->value => 'Could not modify relation, invalid relationinfos given',
            self::Could_Not_Modify_Relation_Relation_Is_Not_Updateable->value => 'Could not modify relation, relation is not updateable',
            self::User_Access_Not_Granted->value => 'User access not granted',
            self::User_Id_Is_Not_Existing_Or_Inactive->value => 'User id is not existing or inactive',
            self::Missing_Or_Invalid_Record_Ids->value => 'Missing or invalid record ids',
            self::Userid_Must_Be_An_Integer->value => 'Userid must be an integer',
            self::Given_Element_Or_Parameter_Was_Not_Expected_To_Be_An_Array->value => 'Given element or parameter was not expected to be an array',
            self::The_User_Data_Could_Not_Be_Found->value => 'The user data could not be found',
            self::The_Transaction_Could_Not_Be_Found->value => 'The transaction could not be found',
            self::The_Time_To_Call_The_Transaction_Has_Expired->value => 'The time to call the transaction has expired',
            self::No_Read_Access_To_Email_Template->value => 'No read access to email template',
            self::Tried_To_Read_Messages_From_An_Unknown_User_Room->value => 'Tried to read messages from an unknown user/room',
            self::Parameter_Extendedclaim_Is_Required_But_Missing_Empty_Or_Invalid->value => 'Parameter extendedclaim is required, but missing, empty or invalid',
            self::Wrong_Type_For_At_Least_One_Of->value => 'Wrong type for at least one of %s',
            self::Parameter_Objids_Is_Required_But_Missing->value => 'Parameter objids is required, but missing',
            self::Resourceid_Is_No_Main_Id->value => 'Resourceid %s is no main Id',
            self::Not_Implemented->value => 'Not implemented',
            self::Parameter_Extendedclaim_Is_Outdated->value => 'Parameter "extendedclaim" is outdated',
            self::Invalid_Username_Or_Password_For_Z_Push_Login->value => 'Invalid username or password for Z-Push login',
            self::Z_Push_Account_Locked_Too_Many_Invalid_Login_Requests->value => 'Z-Push account locked. Too many invalid login requests',
            self::Unknown_Searchcriteria_Mode->value => 'Unknown searchcriteria mode',
            self::Transaction_Id_Does_Not_Match_To_The_Customer->value => 'Transaction-Id does not match to the customer: %s!',
            self::Unknown_Z_Push_Address_Phone_Mapping->value => 'Unknown Z-Push address phone mapping %s',
            self::Empty_Z_Push_Address_Phone_Mapping->value => 'Empty Z-Push address phone mapping',
            self::Using_Parameter_Zpmapping_Is_Not_Allowed_When_Using_Other_Parameters_For_Phone_Fax_Email->value => 'Using parameter zpmapping is not allowed when using other parameters for phone/fax/email.',
            self::Missing_Key_Value_S_In_Zpmapping->value => 'Missing key value(s) in zpmapping: %s.',
            self::Transaction_Can_T_Be_Refunded->value => 'Transaction can\'t be refunded: %s.',
            self::Email_Could_Not_Be_Sent->value => 'Email could not be sent!',
            self::Unknown_Sort_Field->value => 'Unknown sort field.',
            self::Invalid_Filename->value => 'Invalid filename',
            self::Invalid_Price_Format->value => 'Invalid price format!',
            self::Parameter_Must_Not_Be_Null->value => 'Parameter %s must not be null!',
            self::Sync_Module_For_Customer_Is_Not_Active->value => 'Sync module for customer is not active!',
            self::Sync_Outlooksync_Flag_For_Enterprise_User_Is_Disabled->value => 'Sync (Outlooksync) flag for enterprise user is disabled!',
            self::ZPush_Is_Not_Active_For_This_User->value => 'ZPush is not active for this user!',
            self::N_N_Relations_Are_Not_Allowed->value => 'n:n relations are not allowed',
            self::Unknown_Origincontact->value => 'unknown origincontact: %s',
            self::Unknown_Feature->value => 'unknown feature: %s',
            self::Invalid_Value_For_Cost_Not_Numeric_Or_Less_Than_0->value => 'invalid value for cost: not numeric or less than 0: %s',
            self::Invalid_Value_For_Duration_Not_Numeric_Or_Less_Than_0->value => 'invalid value for duration: not numeric or less than 0: %s',
            self::Can_Not_Set_Reason_Of_Cancellation_Advisory_Level_Missing->value => 'can not set reason of cancellation: advisory level missing',
            self::Unknown_Advisory_Level->value => 'unknown advisory level: %s',
            self::Unknown_Reason_Of_Cancelation->value => 'unknown reason of cancelation: %s',
            self::Given_Element_Or_Parameter_Was_Expected_To_Be_A_String->value => 'Given element or parameter was expected to be a string: %s',
            self::Given_Element_Or_Parameter_Was_Expected_To_Be_An_Integer->value => 'Given element or parameter was expected to be an integer: %s',
            self::Given_Element_Or_Parameter_Was_Expected_To_Be_An_Float->value => 'Given element or parameter was expected to be an float: %s',
            self::Missing_Date_Interval->value => 'missing date interval',
            self::Invalid_Date_Interval->value => 'invalid date interval',
            self::Multiselect_Fields_Can_Only_Be_Filtered_With->value => 'Multiselect fields can only be filtered with =, !=, like, not like, in and not in',
            self::Missing_Email_Template->value => 'missing email template',
            self::Unknown_Record_Id->value => 'Unknown record id %s',
            self::Parameter_Data_Must_Be_Of_Type_String->value => 'Parameter "data" must be of type string',
            self::Missing_Filter_Beratungsebene_For->value => 'Missing Filter Beratungsebene for %s',
            self::The_Attachment_Is_Too_Big->value => 'the attachment is too big',
            self::Upload_Failed_Estate_Already_Has_A_Title_Picture->value => 'Upload failed. Estate already has a title picture.',
            self::Call_For_Marketplace_Api_Users_Not_Allowed->value => 'Call for Marketplace Api-Users not allowed',
            self::Filters_Can_Only_Be_Used_When_Reading_Out_Appointments_Of_A_Period->value => 'Filters can only be used when reading out appointments of a period.',
            self::While_Sending_The_Size_Of_The_Attachment_May_Have_Been_Exceeded->value => 'Error while sending. The size of the attachment may have been exceeded.',
            self::The_HMAC_Is_Invalid_Should_Be_Passed_As_String->value => 'The HMAC is invalid. "%s" should be passed as string',
            self::When_Attaching_An_Expose_Only_One_Pdf_Letter_Can_Be_Attached->value => 'When attaching an exposé only one pdf letter can be attached',
            self::No_Read_Access_To_Pdf_Form->value => 'No read access to pdf form',
            self::No_Read_Access_To_Pdf_Letter->value => 'No read access to pdf letter',
            self::Missing_Or_Invalid_Element_Action->value => 'Missing or invalid element: action',
            self::No_Matching_Extendedclaim->value => 'No matching extendedclaim',
            self::Invalid_Zpushuuid->value => 'Invalid zpushuuid',
            self::Maximum_Length_300_Of_Zpushuuid_Exceeded->value => 'Maximum length (300) of zpushuuid exceeded',
            self::Unknown_User->value => 'Unknown user %s',
            self::Unknown_Value_In_Select_Field->value => 'Unknown value in select field "%s"',
            self::No_Access_To->value => 'No access to %s',
            self::Missing_Mandatory_Field->value => 'Missing mandatory field "%s"',
            self::Invalid_Value_For_Parameter->value => 'Invalid value for parameter "%s"',
            self::Parameter_Listlimit_Is_Mandatory_And_Must_Be_0->value => 'Parameter listlimit is mandatory and must be 0.',
            self::An_Occurred_While_Validating_The_Filter->value => 'An error occurred while validating the filter: %s',
            self::The_Default_Entry_For_Must_Be_Passed_Also_As_Normal_Private_Or_Business_Entry->value => 'The default entry for %s must be passed also as normal, private or business entry!',
            self::An_Occurred_Modifying_The_Default_Entry->value => 'An error occurred modifying the default entry: %s',
            self::The_Default_Entry_For_Phone_Must_Be_Passed_Also_As_Normal_Private_Business_Or_Mobile_Entry->value => 'The default entry for phone must be passed also as normal, private, business or mobile entry!',
            self::Missing_Write_Right_For_Addresses_With_Ids->value => 'Missing write right for address(es) with id(s) %s',
            self::Missing_Write_Right_For_Estates_With_Ids->value => 'Missing write right for estate(s) with id(s) %s',
            self::Address_Must_Be_A_Real_Estate_Agent->value => 'Address must be a real estate agent',
            self::Too_Many_Items_In_Worklist->value => 'Too many items in worklist',
            self::Too_Few_Items_In_Worklist->value => 'Too few items in worklist',
            self::WorkingList_Name_Already_Exists->value => 'WorkingList name already exists',
            self::Cannot_Set_Visibility->value => 'Cannot set visibility',
            self::Cannot_Set_STV_Flag->value => 'Cannot set STV Flag',
            self::WorkingList_Type_Not_Allowed->value => 'WorkingList type not allowed',
            self::Wrong_Parameter_Type_For->value => 'Wrong parameter type for %s',
            self::Invalid_Web_Expose_Identifier->value => 'Invalid web exposé identifier',
            self::Invalid_Group_ID->value => 'Invalid Group ID',
            self::WorkingList_Name_Cannot_Be_Empty->value => 'WorkingList name cannot be empty',
            self::Mail_Already_Deleted->value => 'Mail already deleted',
            self::Mail_Couldn_t_Be_Deleted->value => 'Mail couldn’t be deleted',
            self::Mail_Could_Not_Be_Found->value => 'Mail could not be found',
            self::Mail_Couldn_t_Be_Moved->value => 'Mail couldn’t be moved',
            self::Deauthenticate_Can_Only_Be_Called_At_The_End->value => 'Deauthenticate can only be called at the end',
            self::Unknown_ResourceId->value => 'Unknown resourceId',
            self::Flag_Could_Not_Be_Set->value => 'Flag could not be set',
            self::No_Valid_Parameter_Given->value => 'No valid parameter given!',
            self::Email_Could_Not_Be_Found->value => 'Email could not be found!',
            self::The_Requested_Filterid_Is_Unknown->value => 'The requested filterid %s is unknown',
            self::Mail_Could_Not_Be_Loaded->value => 'Mail could not be loaded',
            self::User_Is_Not_Active_286->value => 'User %s is not active',
            self::Folder_Not_Found->value => 'Folder not found!',
            self::Start_Modified_Date_Is_Greater_Than_End_Modified_Date->value => 'Start modified date is greater than end modified date',
            self::Missing_Date_Period->value => 'Missing date period',
            self::Parameter_Location_Holds_Wrong_Values->value => 'Parameter location holds wrong values - Keys address, estate, user and group must carry integer values',
            self::Fieldname_Is_Not_A_String->value => 'Fieldname is not a string',
            self::Unknown_Address_Record_Id->value => 'Unknown address record id. Record may not exist or the permission rights are not set accordingly for this action.',
            self::Unknown_Estate_Record_Id->value => 'Unknown estate record id. Record may not exist or the permission rights are not set accordingly for this action.',
            self::Invalid_Data_Type_For_Parameter->value => 'Invalid data type for parameter %s',
            self::Given_Groups_Has_To_Be_An_Array_Of_IDs->value => 'Given groups has to be an array of IDs',
            self::Either_AddressId_Or_AddressIds_Is_Allowed->value => 'Either addressId or addressIds is allowed. Both are given.',
            self::AddressIds_Must_Be_Of_Type_Array->value => 'AddressIds must be of type array',
            self::AddressIds_Values_Must_Be_Of_Type_Integer->value => 'AddressIds values must be of type integer',
            self::Invalid_Address_Phone_Value->value => 'Invalid address phone value',
            self::Given_Users_Has_To_Be_An_Array_Of_IDs->value => 'Given users has to be an array of IDs',
            self::This_Action_Support_Only_Up_To_500_Ids->value => 'This action support only up to 500 Ids',
            self::Error_Creating_Request->value => 'Error creating request',
            self::Module_And_View_Parameters_Must_Not_Be_Empty->value => 'Module and view parameters must not be empty',

            self::UNKNOWN->value => 'unknown error',
        ];
    }

    public function toString(): string
    {
        return data_get(self::errorTexts(), $this->value, 'unknown error');
    }
}
